app: hello
env: tunnel
providers:
  infra: hetzner
  storage: cloudflare
  dns: cloudflare
  ingress: cloudflare
ssh_key: ~/.ssh/id_rsa.pub
servers:
  master: { type: cax11, region: nbg1, role: master }
services:
  whoami:
    image: traefik/whoami
    port: 80
domains:
  whoami: [tunnel.nvoi.to]
